"""added order number to playlist_song

Revision ID: 236a3e95674a
Revises: 1fbfd8190b7c
Create Date: 2024-11-07 14:49:57.985996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236a3e95674a'
down_revision = '1fbfd8190b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
